# Generated by Django 6.0.6 on 2026-06-27 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('LEAVE_APPROVED', 'Leave Approved'), ('LEAVE_REJECTED', 'Leave Rejected'), ('PERMISSION_APPROVED', 'Permission Approved'), ('PERMISSION_REJECTED', 'Permission Rejected'), ('BIRTHDAY', 'Birthday'), ('ANNIVERSARY', 'Work Anniversary'), ('PENDING_APPROVAL', 'Pending Approval'), ('GENERAL', 'General')], default='GENERAL', max_length=30),
        ),
    ]
