# Generated by Django 6.0.6 on 2026-06-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_production_hardening'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status'], name='projects_pr_status_f023cb_idx'),
        ),
        migrations.AddIndex(
            model_name='projectallocation',
            index=models.Index(fields=['employee', 'released_on'], name='projects_pr_employe_99b368_idx'),
        ),
        migrations.AddIndex(
            model_name='projectallocation',
            index=models.Index(fields=['project', 'released_on'], name='projects_pr_project_f7d4c4_idx'),
        ),
    ]
