# Generated by Django 6.0.6 on 2026-06-27 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_production_hardening'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectallocation',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectallocation',
            name='responsibilities',
            field=models.TextField(blank=True),
        ),
    ]
