# Generated by Django 6.0.6 on 2026-06-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_production_hardening'),
        ('leaves', '0003_permission'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='leave',
            index=models.Index(fields=['employee', 'status'], name='leaves_leav_employe_d3bf49_idx'),
        ),
        migrations.AddIndex(
            model_name='leave',
            index=models.Index(fields=['status', '-created_at'], name='leaves_leav_status_4ae1d7_idx'),
        ),
        migrations.AddIndex(
            model_name='leave',
            index=models.Index(fields=['leave_type'], name='leaves_leav_leave_t_2521b7_idx'),
        ),
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['employee', 'status'], name='leaves_perm_employe_e39ec0_idx'),
        ),
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['date'], name='leaves_perm_date_109a88_idx'),
        ),
    ]
