# Generated by Django 6.0.6 on 2026-06-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_seed_categories'),
        ('employees', '0005_production_hardening'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='employeedocument',
            index=models.Index(fields=['employee', '-uploaded_at'], name='documents_e_employe_47cf65_idx'),
        ),
        migrations.AddIndex(
            model_name='employeedocument',
            index=models.Index(fields=['category'], name='documents_e_categor_e28823_idx'),
        ),
    ]
