# Generated by Django 6.0.6 on 2026-06-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_production_hardening'),
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='salaryrecord',
            index=models.Index(fields=['period'], name='payroll_sal_period_69b38a_idx'),
        ),
        migrations.AddIndex(
            model_name='salaryrecord',
            index=models.Index(fields=['employee', '-period'], name='payroll_sal_employe_2424b3_idx'),
        ),
    ]
