# Generated by Django 6.0.6 on 2026-06-18 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_bankdetails_education_emergencycontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='branch',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
