# Generated by Django 6.0.6 on 2026-06-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_bankdetails_branch_education_university_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['status'], name='employees_e_status_61c2f6_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['department'], name='employees_e_departm_99b42d_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['branch'], name='employees_e_branch_0ed0e4_idx'),
        ),
    ]
